### ISSUE TITLE
Does it work on the latest discourse version?

### ISSUE THREAD

**Issue by cristiangauma** [shivpkumar/Solved-Button#2]
Hi!

I have a question, does it work on the latest discourse version?

I tried to install it, it seems to be installed properly, but I haven't see any button to choose the right post. The installation process that I'm following is:
- Git Clone to the pugins folder
- bundle exec rake assets:precompile 

Other plugins work as expected, but this isn't working.

Any advice?

**Comment by cristiangauma** [comment]
For those who have the same problem: Go to your Admin panel -> Basic Settings and pon post_menu options add "|correct" at the end.

Thanks.

**Comment by shivpkumar** [comment]
Hi @cristiangauma.  Apologies for the late reply here.  Glad you were able to get this to work.  If you have any input on how to make this plugin better, please let me know... or feel free to create a PR.  I'd be happy to review it!
